<?php

/*
 * This file is part of blomstra/digest.
 *
 * Copyright (c) 2022 Team Blomstra.
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Schema\Builder;

return [
    'up' => function (Builder $schema) {
        $schema->create('digest_batches', function (Blueprint $table) {
            // Both IDs are strings generated by the queue driver and the digest aggregator. They don't have any foreign keys
            $table->string('job_id')->primary();
            $table->string('batch_id')->index();

            // The date isn't actually useful to the extension, but it could be used to clean up stale data
            // Though everything should always get deleted automatically unless the queue worker itself crashes mid-job
            $table->timestamp('queued_at');
        });
    },
    'down' => function (Builder $schema) {
        $schema->dropIfExists('digest_batches');
    },
];
